const defaultBidders = [
  //mr. whalen
  "Mr. Whalen",

  //advanced class
  "Noah Abbas",
  "Batyrkhan Alimzhanov",
  "Alexander Atanassov",
  "Kevin Chen",
  "Ryan Chen",
  "Timothy Deng",
  "Sophie Dong",
  "Leo Dwi",
  "Bridget Feng",
  "Veronica Frid",
  "Evan Gao",
  "Rylan Geykhman",
  "Daria Golitsyna",
  "Andrea Guo",
  "Tina Guo",
  "Katie Khamarkhanova",
  "Samuel Kipnis",
  "Abigail Labanok",
  "Angelina Li",
  "Lawrence Lo",
  "Gabriel Liberov",
  "Richard Masak",
  "Konstantin Maslov",
  "Kenneth Ng",
  "Oleg Ponyatyshyn",
  "Noah Rozin",
  "Simon Saffayeh",
  "Bogdan Selyomin",
  "Maximilian Shabatayev",
  "Nicole Soltsov",
  "Yi Xia",
  "Katherine Zeng",
  "Yifan Zhang",
  "Yizhak Zoltan",

  //pd 6 ap comp sci
  "Matthew Baskevich",
  "Thomas Brown",
  "Celine Chan",
  "Benson Chen",
  "Elisa Chen",
  "Ryan Chen",
  "Selina Chen",
  "Kristina Chu",
  "Alexander Dong",
  "Raymond Dong",
  "Wilson Dong",
  "Mark Fridlin",
  "Sidh Gupta",
  "Isaac Hom",
  "Jonathan Hung",
  "Dylan Jiang",
  "Jacky Jiang",
  "Deniz Kirbiyik",
  "Kitson Lau",
  "Agnes Lin",
  "Audrey Lin",
  "Josephine Liu",
  "Jonathan Ou",
  "Leo Ou Yang",
  "Kaden Pang",
  "Kyle Salowitz",
  "Yaolin Tan",
  "Judy Yan",
  "Emerson Yang",
  "Chuyuan Zhang",
  "Haobin Zhao",
  "Jefferson Zheng",
  "Kai Zhong-Jing",
];
export { defaultBidders };
